# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c0a87ef1fc6f9dc5a58b2bd5db13f9b3ce82240683c5a661fb936e84319abac9bf420811d70028486ffbb621ac5a14fa8780dbd8e5c64f14d9b0773a81d8a5

test:
  secret_key_base: 072939254f8a995e164b4f645e9966cbc8a300604872560c88a7bb6b45d32909778882068fe4f6832d359630faa9480d73ac7f3dd73986283d94a374619e4329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
